name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: CI
        run: make install

      - name: Lint
        run: make lint

      - name: Tests
        run: make test
      - name: Test coverage
        run: make test-coverage
